export enum TASKS_ACTION_TYPES {
    FETCH_TASKS_START   = 'tasks/FETCH_TASKS_START',
    FETCH_TASKS_SUCCESS = 'tasks/FETCH_TASKS_SUCCESS',
    FETCH_TASKS_FAILED  = 'tasks/FETCH_TASKS_FAILED',

    CREATE_TASK_START   = 'tasks/CREATE_TASK_START',
    CREATE_TASK_SUCCESS = 'tasks/CREATE_TASK_SUCCESS',
    CREATE_TASK_FAILED  = 'tasks/CREATE_TASK_FAILED',

    DELETE_TASK_START   = 'tasks/DELETE_TASK_START',
    DELETE_TASK_SUCCESS = 'tasks/DELETE_TASK_SUCCESS',
    DELETE_TASK_FAILED  = 'tasks/DELETE_TASK_FAILED',
}

